# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: my@mail.com
author_name: harshita428
contract_name: saving_app
deployment_language: python
preset_name: starter
project_name: algohack-contracts

